# Generated by Django 4.2.2 on 2023-06-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_account_email_alter_account_first_name_and_more'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Post',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, help_text='Name of image for the post', null=True, upload_to='uploads/photos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Text of the post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of the post', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Name of the tag for the post', max_length=50, verbose_name='Name'),
        ),
    ]
