# Generated by Django 4.2.2 on 2023-06-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_follow'),
        ('post', '0002_remove_image_post_remove_post_tags_remove_post_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Post')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Post Archive?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('tags', models.ManyToManyField(related_name='posts_tags', to='post.tag', verbose_name='Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
    ]
