# Generated by Django 4.2.2 on 2023-06-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Post',
            new_name='post',
        ),
    ]
