# Generated by Django 4.2.2 on 2023-06-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
