# Generated by Django 4.2.2 on 2023-06-20 01:33

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number is not correct', regex='\\A(09)(0|1|2|3)[0-9]{7}\\d\\Z')], verbose_name='Phone Number')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('bio', models.CharField(blank=True, help_text="Biography is a written account of a person's life", max_length=150, null=True, verbose_name='Biography')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/photos', verbose_name='Image')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.TimeStampMixin),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user.account')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user.account')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.TimeStampMixin),
        ),
    ]
