# Generated by Django 4.2.2 on 2023-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='Image')),
                ('bio', models.CharField(max_length=150, verbose_name='Bio')),
                ('user_name', models.CharField(max_length=50, verbose_name='User Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('acctive', models.BooleanField(default=False, verbose_name='Is Active Account?')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
            },
        ),
    ]
