# Generated by Django 4.2.2 on 2023-06-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_remove_myuser_following_delete_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
